/* Checks that the package entry points are valid in both places the package is consumed from:
   - the package root (`package.json`, paths into `dist/`) — used inside this workspace and by the changesets release;
   - `dist/` (`dist/package.json`, generated by ng-packagr) — what `pack:dist` puts in the tarball.

   ng-packagr writes its own `.` entry into `dist/package.json` but copies other subpath exports verbatim, so the two
   files cannot hold identical paths. What must hold: both expose the same export keys, and every path in either file
   exists relative to that file. */
import { accessSync, constants, readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const readJSON = (path) => JSON.parse(readFileSync(resolve(here, path), 'utf8'));

const manifests = [
  { name: 'package.json', base: here, pkg: readJSON('package.json') },
  { name: 'dist/package.json', base: resolve(here, 'dist'), pkg: readJSON('dist/package.json') },
];

const pathsOf = (pkg) => [
  pkg.module,
  pkg.typings,
  ...Object.values(pkg.exports ?? {}).flatMap((entry) => (typeof entry === 'string' ? [entry] : Object.values(entry))),
];

const errors = [];

const [root, dist] = manifests;
const rootKeys = Object.keys(root.pkg.exports ?? {}).sort();
const distKeys = Object.keys(dist.pkg.exports ?? {}).sort();
if (JSON.stringify(rootKeys) !== JSON.stringify(distKeys)) {
  errors.push(
    `Export keys differ:\n  package.json:      ${rootKeys.join(', ')}\n  dist/package.json: ${distKeys.join(', ')}`,
  );
}

for (const { name, base, pkg } of manifests) {
  for (const path of pathsOf(pkg).filter(Boolean)) {
    try {
      accessSync(resolve(base, path), constants.R_OK);
      console.log(`${name}: ${path} ✓`);
    } catch {
      errors.push(`${name}: ${path} does not exist (resolved from ${base})`);
    }
  }
}

if (errors.length > 0) {
  throw new Error(`Package entry points are broken. See CONTRIBUTING.md.\n${errors.join('\n')}`);
}
