name: Continuous Delivery

on:
  push:
    branches:
      - main

jobs:
  continuous-delivery:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: install, build, lint and test
        env:
          PUBLIC_URL: .
        run: |
          npm ci
          npm run bootstrap
          npm run build
          npm run lint
          npm run test

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: dist/storybook
